### ISSUE TITLE
Not understand data class constructors

### ISSUE THREAD

**Issue by Just-D-A** [Omega-R/OmegaLint#42]
// TODO mock
data class GeneralSettings(
    var doorStatus: DoorStatus = DoorStatus.CLOSED,
    var keepDoorOpen: Boolean = false,
    var keepDoorOpenSip: Boolean = false,
    var doorOpenDuration: Int = 5,
    var callDuration: Int = 5,
    var talkDuration: Int = 5,
    var conciergeApartment: Int = 100,
    var relayStatus: RelayStatus = RelayStatus.FINE_OPENED
) : Serializable

**Comment by Just-D-A** [comment]
parse in JAVA:
public static final class GeneralSettings {
private int doorStatus;
private boolean keepDoorOpen;
private boolean keepDoorOpenSip;
private int doorOpenDuration;
private int callDuration;
private int talkDuration;
private int conciergeApartment;
private final int conciergeApartment1;
private int conciergeApartment2;
private final int conciergeApartment3;
private int conciergeApartment5;

  public final int getDoorStatus() {
     return this.doorStatus;
  }

  public final void setDoorStatus(int var1) {
     this.doorStatus = var1;
  }

  public final boolean getKeepDoorOpen() {
     return this.keepDoorOpen;
  }

  public final void setKeepDoorOpen(boolean var1) {
     this.keepDoorOpen = var1;
  }

  public final boolean getKeepDoorOpenSip() {
     return this.keepDoorOpenSip;
  }

  public final void setKeepDoorOpenSip(boolean var1) {
     this.keepDoorOpenSip = var1;
  }

**Comment by DimaSidukov** [comment]
более не воспроизводится
